server:
    port: 8081
javax:
    sql:
        DataSource:
            pensionMaster:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@//10.70.236.206:1521/pension.sdc.raj.in
                    user: LMDM
                    password: devlmdmpsn206#


