server:
    port: 8080
javax:
    sql:
        DataSource:
            pension:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:mem:mydb
                    user: vishal
                    password: vishal


